### ISSUE TITLE
postOrder parameters

### ISSUE THREAD

**Issue by asterioslaskaroglou** [westwinglabs/coinbase-kotlin#19]
Hello,
postOrder function doesn't accept any parameters. 
How do i send the mandatory fields "size" "price" "side" and "product_id".
Can you please direct me to any documentation?
Thanks for the nice job.

**Comment by zugaldia** [comment]
@asterioslaskaroglou Thanks for the ticket and for trying the library. I'm adding support for those parameters with https://github.com/westwinglabs/coinbase-kotlin/pull/23, which will be available in v0.4.0.

I'm planning the release as soon as I migrate the project out from Bintray (which is being deprecated).
